//
// Generated file, do not edit! Created by nedtool 5.5 from Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Packet.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Packet
 * {
 *     int id_aircraft;
 *     int id_baseStation;
 * 
 *     double x_aircraft;
 *     double y_aircraft;
 *     double distant_AC_BS;
 * 
 *     double departureAC_time;
 *     double arrivalBS_time;
 *     double departureBS_time;
 *     double arrivalCT_time;
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cMessage
{
  protected:
    int id_aircraft;
    int id_baseStation;
    double x_aircraft;
    double y_aircraft;
    double distant_AC_BS;
    double departureAC_time;
    double arrivalBS_time;
    double departureBS_time;
    double arrivalCT_time;

  private:
    void copy(const Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Packet&);

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId_aircraft() const;
    virtual void setId_aircraft(int id_aircraft);
    virtual int getId_baseStation() const;
    virtual void setId_baseStation(int id_baseStation);
    virtual double getX_aircraft() const;
    virtual void setX_aircraft(double x_aircraft);
    virtual double getY_aircraft() const;
    virtual void setY_aircraft(double y_aircraft);
    virtual double getDistant_AC_BS() const;
    virtual void setDistant_AC_BS(double distant_AC_BS);
    virtual double getDepartureAC_time() const;
    virtual void setDepartureAC_time(double departureAC_time);
    virtual double getArrivalBS_time() const;
    virtual void setArrivalBS_time(double arrivalBS_time);
    virtual double getDepartureBS_time() const;
    virtual void setDepartureBS_time(double departureBS_time);
    virtual double getArrivalCT_time() const;
    virtual void setArrivalCT_time(double arrivalCT_time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKET_M_H

