//
// Generated file, do not edit! Created by nedtool 5.5 from Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Packet.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message Packet
 * {
 *     int id_aircraft;
 *     int id_baseStation;
 *     int queueCount;
 *     double x_aircraft;
 *     double y_aircraft;
 *     double distance_AC_BS;
 *     simtime_t serviceTime;
 *     simtime_t creationTime;
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cMessage
{
  protected:
    int id_aircraft;
    int id_baseStation;
    int queueCount;
    double x_aircraft;
    double y_aircraft;
    double distance_AC_BS;
    ::omnetpp::simtime_t serviceTime;
    ::omnetpp::simtime_t creationTime;

  private:
    void copy(const Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Packet&);

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getId_aircraft() const;
    virtual void setId_aircraft(int id_aircraft);
    virtual int getId_baseStation() const;
    virtual void setId_baseStation(int id_baseStation);
    virtual int getQueueCount() const;
    virtual void setQueueCount(int queueCount);
    virtual double getX_aircraft() const;
    virtual void setX_aircraft(double x_aircraft);
    virtual double getY_aircraft() const;
    virtual void setY_aircraft(double y_aircraft);
    virtual double getDistance_AC_BS() const;
    virtual void setDistance_AC_BS(double distance_AC_BS);
    virtual ::omnetpp::simtime_t getServiceTime() const;
    virtual void setServiceTime(::omnetpp::simtime_t serviceTime);
    virtual ::omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(::omnetpp::simtime_t creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKET_M_H

